### ISSUE TITLE
Reason to mount /opt/liferay

### ISSUE THREAD

**Issue by GerardSetho** [rsippl/docker-liferay-7.0#1]
Hi Ralf,

Quick question: why is the `/opt/liferay` a mountable volume?

`VOLUME ["/opt/liferay"]`

Should I copy the entire `/opt/liferay` directory to a source folder (e.g. on the host) and then mount to `/opt/liferay`? I only ask this because I might want to edit some of the properties files (e.g. `portal-ext.properties`)

**Comment by rsippl** [comment]
The VOLUME line is probably not necessary. In your case, I guess you could use something like
`-v ~/portal-ext.properties:/opt/liferay/portal-ext.properties`
when creating the container.

**Comment by GerardSetho** [comment]
Thanks! Closing.
